# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AffinityIos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.4'
    pod 'Toast-Swift', '~> 2.0.0'
    pod 'ImageSlideshow/Alamofire'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'Google/SignIn'
    pod 'SwiftyJSON'
    pod 'SideMenu'
    pod 'KYCircularProgress'
    pod 'KDCircularProgress'
    pod 'CryptoSwift'
    pod 'Branch'
  # Pods for AffinityIos

  target 'AffinityIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AffinityIosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
